// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ActivityCreditWallet struct {
	Data *FlowsCreditWalletRequest `json:"data,omitempty"`
	ID   *string                   `json:"id,omitempty"`
}

func (a *ActivityCreditWallet) GetData() *FlowsCreditWalletRequest {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *ActivityCreditWallet) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}
