// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ActivityCreateTransactionOutput struct {
	Data FlowsTransaction `json:"data"`
}

func (a *ActivityCreateTransactionOutput) GetData() FlowsTransaction {
	if a == nil {
		return FlowsTransaction{}
	}
	return a.Data
}
