// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ActivityDebitWalletOutput struct {
	Data FlowsHold `json:"data"`
}

func (a *ActivityDebitWalletOutput) GetData() FlowsHold {
	if a == nil {
		return FlowsHold{}
	}
	return a.Data
}
