// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ActivityGetAccountOutput struct {
	Data FlowsAccount `json:"data"`
}

func (a *ActivityGetAccountOutput) GetData() FlowsAccount {
	if a == nil {
		return FlowsAccount{}
	}
	return a.Data
}
