// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ActivityGetPaymentOutput struct {
	Data FlowsPayment `json:"data"`
}

func (a *ActivityGetPaymentOutput) GetData() FlowsPayment {
	if a == nil {
		return FlowsPayment{}
	}
	return a.Data
}
