// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
	"time"
)

type FlowsTransaction struct {
	ID        *big.Int          `json:"id"`
	Metadata  map[string]string `json:"metadata"`
	Postings  []Posting         `json:"postings"`
	Reference *string           `json:"reference,omitempty"`
	Reverted  bool              `json:"reverted"`
	Timestamp time.Time         `json:"timestamp"`
}

func (f FlowsTransaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowsTransaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"id", "metadata", "postings", "reverted", "timestamp"}); err != nil {
		return err
	}
	return nil
}

func (f *FlowsTransaction) GetID() *big.Int {
	if f == nil {
		return big.NewInt(0)
	}
	return f.ID
}

func (f *FlowsTransaction) GetMetadata() map[string]string {
	if f == nil {
		return map[string]string{}
	}
	return f.Metadata
}

func (f *FlowsTransaction) GetPostings() []Posting {
	if f == nil {
		return []Posting{}
	}
	return f.Postings
}

func (f *FlowsTransaction) GetReference() *string {
	if f == nil {
		return nil
	}
	return f.Reference
}

func (f *FlowsTransaction) GetReverted() bool {
	if f == nil {
		return false
	}
	return f.Reverted
}

func (f *FlowsTransaction) GetTimestamp() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.Timestamp
}
