// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type FlowsAccount struct {
	Address          string            `json:"address"`
	EffectiveVolumes map[string]Volume `json:"effectiveVolumes,omitempty"`
	Metadata         map[string]string `json:"metadata"`
	Volumes          map[string]Volume `json:"volumes,omitempty"`
}

func (f *FlowsAccount) GetAddress() string {
	if f == nil {
		return ""
	}
	return f.Address
}

func (f *FlowsAccount) GetEffectiveVolumes() map[string]Volume {
	if f == nil {
		return nil
	}
	return f.EffectiveVolumes
}

func (f *FlowsAccount) GetMetadata() map[string]string {
	if f == nil {
		return map[string]string{}
	}
	return f.Metadata
}

func (f *FlowsAccount) GetVolumes() map[string]Volume {
	if f == nil {
		return nil
	}
	return f.Volumes
}
