// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type FlowsPaymentStatus string

const (
	FlowsPaymentStatusPending    FlowsPaymentStatus = "PENDING"
	FlowsPaymentStatusActive     FlowsPaymentStatus = "ACTIVE"
	FlowsPaymentStatusTerminated FlowsPaymentStatus = "TERMINATED"
	FlowsPaymentStatusFailed     FlowsPaymentStatus = "FAILED"
	FlowsPaymentStatusSucceeded  FlowsPaymentStatus = "SUCCEEDED"
	FlowsPaymentStatusCancelled  FlowsPaymentStatus = "CANCELLED"
)

func (e FlowsPaymentStatus) ToPointer() *FlowsPaymentStatus {
	return &e
}
func (e *FlowsPaymentStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PENDING":
		fallthrough
	case "ACTIVE":
		fallthrough
	case "TERMINATED":
		fallthrough
	case "FAILED":
		fallthrough
	case "SUCCEEDED":
		fallthrough
	case "CANCELLED":
		*e = FlowsPaymentStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FlowsPaymentStatus: %v", v)
	}
}
