// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type FlowsV2Account struct {
	Address          string              `json:"address"`
	EffectiveVolumes map[string]V2Volume `json:"effectiveVolumes,omitempty"`
	Metadata         map[string]string   `json:"metadata"`
	Volumes          map[string]V2Volume `json:"volumes,omitempty"`
}

func (f *FlowsV2Account) GetAddress() string {
	if f == nil {
		return ""
	}
	return f.Address
}

func (f *FlowsV2Account) GetEffectiveVolumes() map[string]V2Volume {
	if f == nil {
		return nil
	}
	return f.EffectiveVolumes
}

func (f *FlowsV2Account) GetMetadata() map[string]string {
	if f == nil {
		return map[string]string{}
	}
	return f.Metadata
}

func (f *FlowsV2Account) GetVolumes() map[string]V2Volume {
	if f == nil {
		return nil
	}
	return f.Volumes
}
