// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type FlowsListWalletsResponseCursor struct {
	Data     []FlowsWallet `json:"data"`
	HasMore  *bool         `json:"hasMore,omitempty"`
	Next     *string       `json:"next,omitempty"`
	PageSize int64         `json:"pageSize"`
	Previous *string       `json:"previous,omitempty"`
}

func (f *FlowsListWalletsResponseCursor) GetData() []FlowsWallet {
	if f == nil {
		return []FlowsWallet{}
	}
	return f.Data
}

func (f *FlowsListWalletsResponseCursor) GetHasMore() *bool {
	if f == nil {
		return nil
	}
	return f.HasMore
}

func (f *FlowsListWalletsResponseCursor) GetNext() *string {
	if f == nil {
		return nil
	}
	return f.Next
}

func (f *FlowsListWalletsResponseCursor) GetPageSize() int64 {
	if f == nil {
		return 0
	}
	return f.PageSize
}

func (f *FlowsListWalletsResponseCursor) GetPrevious() *string {
	if f == nil {
		return nil
	}
	return f.Previous
}

type FlowsListWalletsResponse struct {
	Cursor FlowsListWalletsResponseCursor `json:"cursor"`
}

func (f *FlowsListWalletsResponse) GetCursor() FlowsListWalletsResponseCursor {
	if f == nil {
		return FlowsListWalletsResponseCursor{}
	}
	return f.Cursor
}
