// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"time"
)

type FlowsV2PostTransactionScript struct {
	Plain string         `json:"plain"`
	Vars  map[string]any `json:"vars,omitempty"`
}

func (f *FlowsV2PostTransactionScript) GetPlain() string {
	if f == nil {
		return ""
	}
	return f.Plain
}

func (f *FlowsV2PostTransactionScript) GetVars() map[string]any {
	if f == nil {
		return nil
	}
	return f.Vars
}

type FlowsV2PostTransaction struct {
	Metadata  map[string]string             `json:"metadata"`
	Postings  []V2Posting                   `json:"postings,omitempty"`
	Reference *string                       `json:"reference,omitempty"`
	Script    *FlowsV2PostTransactionScript `json:"script,omitempty"`
	Timestamp *time.Time                    `json:"timestamp,omitempty"`
}

func (f FlowsV2PostTransaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowsV2PostTransaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"metadata"}); err != nil {
		return err
	}
	return nil
}

func (f *FlowsV2PostTransaction) GetMetadata() map[string]string {
	if f == nil {
		return map[string]string{}
	}
	return f.Metadata
}

func (f *FlowsV2PostTransaction) GetPostings() []V2Posting {
	if f == nil {
		return nil
	}
	return f.Postings
}

func (f *FlowsV2PostTransaction) GetReference() *string {
	if f == nil {
		return nil
	}
	return f.Reference
}

func (f *FlowsV2PostTransaction) GetScript() *FlowsV2PostTransactionScript {
	if f == nil {
		return nil
	}
	return f.Script
}

func (f *FlowsV2PostTransaction) GetTimestamp() *time.Time {
	if f == nil {
		return nil
	}
	return f.Timestamp
}
