// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
	"time"
)

type FlowsV2Transaction struct {
	Metadata  map[string]string `json:"metadata"`
	Postings  []V2Posting       `json:"postings"`
	Reference *string           `json:"reference,omitempty"`
	Timestamp time.Time         `json:"timestamp"`
	Txid      *big.Int          `json:"txid"`
}

func (f FlowsV2Transaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowsV2Transaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"metadata", "postings", "timestamp", "txid"}); err != nil {
		return err
	}
	return nil
}

func (f *FlowsV2Transaction) GetMetadata() map[string]string {
	if f == nil {
		return map[string]string{}
	}
	return f.Metadata
}

func (f *FlowsV2Transaction) GetPostings() []V2Posting {
	if f == nil {
		return []V2Posting{}
	}
	return f.Postings
}

func (f *FlowsV2Transaction) GetReference() *string {
	if f == nil {
		return nil
	}
	return f.Reference
}

func (f *FlowsV2Transaction) GetTimestamp() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.Timestamp
}

func (f *FlowsV2Transaction) GetTxid() *big.Int {
	if f == nil {
		return big.NewInt(0)
	}
	return f.Txid
}
