// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"time"
)

type FlowsCreditWalletRequest struct {
	Amount Monetary `json:"amount"`
	// The balance to credit
	Balance *string `json:"balance,omitempty"`
	// Metadata associated with the wallet.
	Metadata  map[string]string `json:"metadata"`
	Reference *string           `json:"reference,omitempty"`
	Sources   []Subject         `json:"sources"`
	Timestamp *time.Time        `json:"timestamp,omitempty"`
}

func (f FlowsCreditWalletRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowsCreditWalletRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"amount", "metadata", "sources"}); err != nil {
		return err
	}
	return nil
}

func (f *FlowsCreditWalletRequest) GetAmount() Monetary {
	if f == nil {
		return Monetary{}
	}
	return f.Amount
}

func (f *FlowsCreditWalletRequest) GetBalance() *string {
	if f == nil {
		return nil
	}
	return f.Balance
}

func (f *FlowsCreditWalletRequest) GetMetadata() map[string]string {
	if f == nil {
		return map[string]string{}
	}
	return f.Metadata
}

func (f *FlowsCreditWalletRequest) GetReference() *string {
	if f == nil {
		return nil
	}
	return f.Reference
}

func (f *FlowsCreditWalletRequest) GetSources() []Subject {
	if f == nil {
		return []Subject{}
	}
	return f.Sources
}

func (f *FlowsCreditWalletRequest) GetTimestamp() *time.Time {
	if f == nil {
		return nil
	}
	return f.Timestamp
}
