// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type FlowsPaymentMetadata struct {
	Key *string `json:"key,omitempty"`
}

func (f *FlowsPaymentMetadata) GetKey() *string {
	if f == nil {
		return nil
	}
	return f.Key
}
