// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"time"
)

type FlowsWallet struct {
	CreatedAt time.Time `json:"createdAt"`
	// The unique ID of the wallet.
	ID     string `json:"id"`
	Ledger string `json:"ledger"`
	// Metadata associated with the wallet.
	Metadata map[string]string `json:"metadata"`
	Name     string            `json:"name"`
}

func (f FlowsWallet) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowsWallet) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"createdAt", "id", "ledger", "metadata", "name"}); err != nil {
		return err
	}
	return nil
}

func (f *FlowsWallet) GetCreatedAt() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.CreatedAt
}

func (f *FlowsWallet) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *FlowsWallet) GetLedger() string {
	if f == nil {
		return ""
	}
	return f.Ledger
}

func (f *FlowsWallet) GetMetadata() map[string]string {
	if f == nil {
		return map[string]string{}
	}
	return f.Metadata
}

func (f *FlowsWallet) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}
