// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"math/big"
	"time"
)

type FlowsPaymentAdjustmentRaw struct {
}

type FlowsPaymentAdjustment struct {
	Absolute bool                      `json:"absolute"`
	Amount   *big.Int                  `json:"amount"`
	Date     time.Time                 `json:"date"`
	Raw      FlowsPaymentAdjustmentRaw `json:"raw"`
	Status   FlowsPaymentStatus        `json:"status"`
}

func (f FlowsPaymentAdjustment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowsPaymentAdjustment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"absolute", "amount", "date", "raw", "status"}); err != nil {
		return err
	}
	return nil
}

func (f *FlowsPaymentAdjustment) GetAbsolute() bool {
	if f == nil {
		return false
	}
	return f.Absolute
}

func (f *FlowsPaymentAdjustment) GetAmount() *big.Int {
	if f == nil {
		return big.NewInt(0)
	}
	return f.Amount
}

func (f *FlowsPaymentAdjustment) GetDate() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.Date
}

func (f *FlowsPaymentAdjustment) GetRaw() FlowsPaymentAdjustmentRaw {
	if f == nil {
		return FlowsPaymentAdjustmentRaw{}
	}
	return f.Raw
}

func (f *FlowsPaymentAdjustment) GetStatus() FlowsPaymentStatus {
	if f == nil {
		return FlowsPaymentStatus("")
	}
	return f.Status
}
