// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"time"
)

type FlowsPostTransactionScript struct {
	Plain string         `json:"plain"`
	Vars  map[string]any `json:"vars,omitempty"`
}

func (f *FlowsPostTransactionScript) GetPlain() string {
	if f == nil {
		return ""
	}
	return f.Plain
}

func (f *FlowsPostTransactionScript) GetVars() map[string]any {
	if f == nil {
		return nil
	}
	return f.Vars
}

type FlowsPostTransaction struct {
	Metadata  map[string]string           `json:"metadata"`
	Postings  []Posting                   `json:"postings,omitempty"`
	Reference *string                     `json:"reference,omitempty"`
	Script    *FlowsPostTransactionScript `json:"script,omitempty"`
	Timestamp *time.Time                  `json:"timestamp,omitempty"`
}

func (f FlowsPostTransaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FlowsPostTransaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"metadata"}); err != nil {
		return err
	}
	return nil
}

func (f *FlowsPostTransaction) GetMetadata() map[string]string {
	if f == nil {
		return map[string]string{}
	}
	return f.Metadata
}

func (f *FlowsPostTransaction) GetPostings() []Posting {
	if f == nil {
		return nil
	}
	return f.Postings
}

func (f *FlowsPostTransaction) GetReference() *string {
	if f == nil {
		return nil
	}
	return f.Reference
}

func (f *FlowsPostTransaction) GetScript() *FlowsPostTransactionScript {
	if f == nil {
		return nil
	}
	return f.Script
}

func (f *FlowsPostTransaction) GetTimestamp() *time.Time {
	if f == nil {
		return nil
	}
	return f.Timestamp
}
