// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type FlowsHold struct {
	Description string   `json:"description"`
	Destination *Subject `json:"destination,omitempty"`
	// The unique ID of the hold.
	ID string `json:"id"`
	// Metadata associated with the hold.
	Metadata map[string]string `json:"metadata"`
	// The ID of the wallet the hold is associated with.
	WalletID string `json:"walletID"`
}

func (f *FlowsHold) GetDescription() string {
	if f == nil {
		return ""
	}
	return f.Description
}

func (f *FlowsHold) GetDestination() *Subject {
	if f == nil {
		return nil
	}
	return f.Destination
}

func (f *FlowsHold) GetDestinationAccount() *LedgerAccountSubject {
	if v := f.GetDestination(); v != nil {
		return v.LedgerAccountSubject
	}
	return nil
}

func (f *FlowsHold) GetDestinationWallet() *WalletSubject {
	if v := f.GetDestination(); v != nil {
		return v.WalletSubject
	}
	return nil
}

func (f *FlowsHold) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *FlowsHold) GetMetadata() map[string]string {
	if f == nil {
		return map[string]string{}
	}
	return f.Metadata
}

func (f *FlowsHold) GetWalletID() string {
	if f == nil {
		return ""
	}
	return f.WalletID
}
