// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type FlowsConnector string

const (
	FlowsConnectorStripe        FlowsConnector = "STRIPE"
	FlowsConnectorDummyPay      FlowsConnector = "DUMMY-PAY"
	FlowsConnectorWise          FlowsConnector = "WISE"
	FlowsConnectorModulr        FlowsConnector = "MODULR"
	FlowsConnectorCurrencyCloud FlowsConnector = "CURRENCY-CLOUD"
	FlowsConnectorBankingCircle FlowsConnector = "BANKING-CIRCLE"
	FlowsConnectorMangopay      FlowsConnector = "MANGOPAY"
	FlowsConnectorMoneycorp     FlowsConnector = "MONEYCORP"
)

func (e FlowsConnector) ToPointer() *FlowsConnector {
	return &e
}
func (e *FlowsConnector) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "STRIPE":
		fallthrough
	case "DUMMY-PAY":
		fallthrough
	case "WISE":
		fallthrough
	case "MODULR":
		fallthrough
	case "CURRENCY-CLOUD":
		fallthrough
	case "BANKING-CIRCLE":
		fallthrough
	case "MANGOPAY":
		fallthrough
	case "MONEYCORP":
		*e = FlowsConnector(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FlowsConnector: %v", v)
	}
}
