// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// PaymentsErrorResponse - Error
type PaymentsErrorResponse struct {
	ErrorCode    PaymentsErrorsEnum `json:"errorCode"`
	ErrorMessage string             `json:"errorMessage"`
}

func (p *PaymentsErrorResponse) GetErrorCode() PaymentsErrorsEnum {
	if p == nil {
		return PaymentsErrorsEnum("")
	}
	return p.ErrorCode
}

func (p *PaymentsErrorResponse) GetErrorMessage() string {
	if p == nil {
		return ""
	}
	return p.ErrorMessage
}
