// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PoolRequest struct {
	AccountIDs []string       `json:"accountIDs,omitempty"`
	Name       string         `json:"name"`
	Query      map[string]any `json:"query,omitempty"`
}

func (p *PoolRequest) GetAccountIDs() []string {
	if p == nil {
		return nil
	}
	return p.AccountIDs
}

func (p *PoolRequest) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PoolRequest) GetQuery() map[string]any {
	if p == nil {
		return nil
	}
	return p.Query
}
