// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ReconciliationErrorResponse - Error response
type ReconciliationErrorResponse struct {
	Details      *string `json:"details,omitempty"`
	ErrorCode    string  `json:"errorCode"`
	ErrorMessage string  `json:"errorMessage"`
}

func (r *ReconciliationErrorResponse) GetDetails() *string {
	if r == nil {
		return nil
	}
	return r.Details
}

func (r *ReconciliationErrorResponse) GetErrorCode() string {
	if r == nil {
		return ""
	}
	return r.ErrorCode
}

func (r *ReconciliationErrorResponse) GetErrorMessage() string {
	if r == nil {
		return ""
	}
	return r.ErrorMessage
}
