// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RevertTransactionResponse struct {
	Data FlowsTransaction `json:"data"`
}

func (r *RevertTransactionResponse) GetData() FlowsTransaction {
	if r == nil {
		return FlowsTransaction{}
	}
	return r.Data
}
