// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2ActivityGetAccountOutput struct {
	Data FlowsV2Account `json:"data"`
}

func (v *V2ActivityGetAccountOutput) GetData() FlowsV2Account {
	if v == nil {
		return FlowsV2Account{}
	}
	return v.Data
}
