// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2ActivityCreateTransaction struct {
	Data   *FlowsV2PostTransaction `json:"data,omitempty"`
	Ledger *string                 `json:"ledger,omitempty"`
}

func (v *V2ActivityCreateTransaction) GetData() *FlowsV2PostTransaction {
	if v == nil {
		return nil
	}
	return v.Data
}

func (v *V2ActivityCreateTransaction) GetLedger() *string {
	if v == nil {
		return nil
	}
	return v.Ledger
}
