// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2ActivityCreateTransactionOutput struct {
	Data []FlowsV2Transaction `json:"data"`
}

func (v *V2ActivityCreateTransactionOutput) GetData() []FlowsV2Transaction {
	if v == nil {
		return []FlowsV2Transaction{}
	}
	return v.Data
}
