// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type V2ErrorErrorCode string

const (
	V2ErrorErrorCodeValidation V2ErrorErrorCode = "VALIDATION"
	V2ErrorErrorCodeNotFound   V2ErrorErrorCode = "NOT_FOUND"
	V2ErrorErrorCodeInternal   V2ErrorErrorCode = "INTERNAL"
)

func (e V2ErrorErrorCode) ToPointer() *V2ErrorErrorCode {
	return &e
}
func (e *V2ErrorErrorCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "VALIDATION":
		fallthrough
	case "NOT_FOUND":
		fallthrough
	case "INTERNAL":
		*e = V2ErrorErrorCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V2ErrorErrorCode: %v", v)
	}
}

// V2Error - General error
type V2Error struct {
	ErrorCode    V2ErrorErrorCode `json:"errorCode"`
	ErrorMessage string           `json:"errorMessage"`
}

func (v *V2Error) GetErrorCode() V2ErrorErrorCode {
	if v == nil {
		return V2ErrorErrorCode("")
	}
	return v.ErrorCode
}

func (v *V2Error) GetErrorMessage() string {
	if v == nil {
		return ""
	}
	return v.ErrorMessage
}
