// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"time"
)

// V2Schema - Complete schema structure with metadata
type V2Schema struct {
	// Schema creation timestamp
	CreatedAt time.Time `json:"createdAt"`
	// Schema data structure for ledger schemas
	Data V2SchemaData `json:"data"`
	// Schema version
	Version string `json:"version"`
}

func (v V2Schema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2Schema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"createdAt", "data", "version"}); err != nil {
		return err
	}
	return nil
}

func (v *V2Schema) GetCreatedAt() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.CreatedAt
}

func (v *V2Schema) GetData() V2SchemaData {
	if v == nil {
		return V2SchemaData{}
	}
	return v.Data
}

func (v *V2Schema) GetVersion() string {
	if v == nil {
		return ""
	}
	return v.Version
}
