// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V2TransactionTemplate struct {
	Description *string `json:"description,omitempty"`
	// The numscript runtime used to execute the script. Uses "machine" by default, unless the "--experimental-numscript-interpreter" feature flag is passed.
	Runtime *Runtime `json:"runtime,omitempty"`
	Script  string   `json:"script"`
}

func (v *V2TransactionTemplate) GetDescription() *string {
	if v == nil {
		return nil
	}
	return v.Description
}

func (v *V2TransactionTemplate) GetRuntime() *Runtime {
	if v == nil {
		return nil
	}
	return v.Runtime
}

func (v *V2TransactionTemplate) GetScript() string {
	if v == nil {
		return ""
	}
	return v.Script
}
