// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V3CreatePoolRequest struct {
	AccountIDs []string       `json:"accountIDs,omitempty"`
	Name       string         `json:"name"`
	Query      map[string]any `json:"query,omitempty"`
}

func (v *V3CreatePoolRequest) GetAccountIDs() []string {
	if v == nil {
		return nil
	}
	return v.AccountIDs
}

func (v *V3CreatePoolRequest) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V3CreatePoolRequest) GetQuery() map[string]any {
	if v == nil {
		return nil
	}
	return v.Query
}
