// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V3ErrorResponse struct {
	Details      *string      `json:"details,omitempty"`
	ErrorCode    V3ErrorsEnum `json:"errorCode"`
	ErrorMessage string       `json:"errorMessage"`
}

func (v *V3ErrorResponse) GetDetails() *string {
	if v == nil {
		return nil
	}
	return v.Details
}

func (v *V3ErrorResponse) GetErrorCode() V3ErrorsEnum {
	if v == nil {
		return V3ErrorsEnum("")
	}
	return v.ErrorCode
}

func (v *V3ErrorResponse) GetErrorMessage() string {
	if v == nil {
		return ""
	}
	return v.ErrorMessage
}
