// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V3PaymentServiceUserDeleteConnectorResponseData struct {
	// Since this call is asynchronous, the response will contain the ID of the task that was created to delete the payment service user on the connector. You can use the task API to check the status of the task.
	//
	TaskID string `json:"taskID"`
}

func (v *V3PaymentServiceUserDeleteConnectorResponseData) GetTaskID() string {
	if v == nil {
		return ""
	}
	return v.TaskID
}

type V3PaymentServiceUserDeleteConnectorResponse struct {
	Data V3PaymentServiceUserDeleteConnectorResponseData `json:"data"`
}

func (v *V3PaymentServiceUserDeleteConnectorResponse) GetData() V3PaymentServiceUserDeleteConnectorResponseData {
	if v == nil {
		return V3PaymentServiceUserDeleteConnectorResponseData{}
	}
	return v.Data
}
