// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V3UpdatePoolQueryRequest struct {
	Query map[string]any `json:"query"`
}

func (v *V3UpdatePoolQueryRequest) GetQuery() map[string]any {
	if v == nil {
		return map[string]any{}
	}
	return v.Query
}
