// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type WalletsErrorResponseErrorCode string

const (
	WalletsErrorResponseErrorCodeValidation       WalletsErrorResponseErrorCode = "VALIDATION"
	WalletsErrorResponseErrorCodeInternalError    WalletsErrorResponseErrorCode = "INTERNAL_ERROR"
	WalletsErrorResponseErrorCodeInsufficientFund WalletsErrorResponseErrorCode = "INSUFFICIENT_FUND"
	WalletsErrorResponseErrorCodeHoldClosed       WalletsErrorResponseErrorCode = "HOLD_CLOSED"
)

func (e WalletsErrorResponseErrorCode) ToPointer() *WalletsErrorResponseErrorCode {
	return &e
}
func (e *WalletsErrorResponseErrorCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "VALIDATION":
		fallthrough
	case "INTERNAL_ERROR":
		fallthrough
	case "INSUFFICIENT_FUND":
		fallthrough
	case "HOLD_CLOSED":
		*e = WalletsErrorResponseErrorCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WalletsErrorResponseErrorCode: %v", v)
	}
}

type WalletsErrorResponse struct {
	ErrorCode    WalletsErrorResponseErrorCode `json:"errorCode"`
	ErrorMessage string                        `json:"errorMessage"`
}

func (w *WalletsErrorResponse) GetErrorCode() WalletsErrorResponseErrorCode {
	if w == nil {
		return WalletsErrorResponseErrorCode("")
	}
	return w.ErrorCode
}

func (w *WalletsErrorResponse) GetErrorMessage() string {
	if w == nil {
		return ""
	}
	return w.ErrorMessage
}
