// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type WebhooksErrorResponse struct {
	Details      *string            `json:"details,omitempty"`
	ErrorCode    WebhooksErrorsEnum `json:"errorCode"`
	ErrorMessage string             `json:"errorMessage"`
}

func (w *WebhooksErrorResponse) GetDetails() *string {
	if w == nil {
		return nil
	}
	return w.Details
}

func (w *WebhooksErrorResponse) GetErrorCode() WebhooksErrorsEnum {
	if w == nil {
		return WebhooksErrorsEnum("")
	}
	return w.ErrorCode
}

func (w *WebhooksErrorResponse) GetErrorMessage() string {
	if w == nil {
		return ""
	}
	return w.ErrorMessage
}
