// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
)

type V2BulkResponse struct {
	Data         []shared.V2BulkElementResult `json:"data,omitempty"`
	ErrorCode    *shared.V2ErrorsEnum         `json:"errorCode,omitempty"`
	ErrorMessage *string                      `json:"errorMessage,omitempty"`
}

var _ error = &V2BulkResponse{}

func (e *V2BulkResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
