// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type DeletePoolRequest struct {
	// The pool ID.
	PoolID string `pathParam:"style=simple,explode=false,name=poolId"`
}

func (d *DeletePoolRequest) GetPoolID() string {
	if d == nil {
		return ""
	}
	return d.PoolID
}

type DeletePoolResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Error
	PaymentsErrorResponse *shared.PaymentsErrorResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeletePoolResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeletePoolResponse) GetPaymentsErrorResponse() *shared.PaymentsErrorResponse {
	if d == nil {
		return nil
	}
	return d.PaymentsErrorResponse
}

func (d *DeletePoolResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeletePoolResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
