// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type FlowsgetServerInfoResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// General error
	Error *shared.Error
	// Server information
	ServerInfo *shared.ServerInfo
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (f *FlowsgetServerInfoResponse) GetContentType() string {
	if f == nil {
		return ""
	}
	return f.ContentType
}

func (f *FlowsgetServerInfoResponse) GetError() *shared.Error {
	if f == nil {
		return nil
	}
	return f.Error
}

func (f *FlowsgetServerInfoResponse) GetServerInfo() *shared.ServerInfo {
	if f == nil {
		return nil
	}
	return f.ServerInfo
}

func (f *FlowsgetServerInfoResponse) GetStatusCode() int {
	if f == nil {
		return 0
	}
	return f.StatusCode
}

func (f *FlowsgetServerInfoResponse) GetRawResponse() *http.Response {
	if f == nil {
		return nil
	}
	return f.RawResponse
}
