// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type GetMetricsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	V2ErrorResponse *shared.V2ErrorResponse
	// OK
	Object map[string]any
}

func (g *GetMetricsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetMetricsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetMetricsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetMetricsResponse) GetV2ErrorResponse() *shared.V2ErrorResponse {
	if g == nil {
		return nil
	}
	return g.V2ErrorResponse
}

func (g *GetMetricsResponse) GetObject() map[string]any {
	if g == nil {
		return nil
	}
	return g.Object
}
