// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"github.com/formancehq/formance-sdk-go/v3/pkg/utils"
	"net/http"
	"time"
)

type V2CountAccountsRequest struct {
	// Name of the ledger.
	Ledger string         `pathParam:"style=simple,explode=false,name=ledger"`
	Pit    *time.Time     `queryParam:"style=form,explode=true,name=pit"`
	Query  map[string]any `queryParam:"serialization=json,name=query"`
}

func (v V2CountAccountsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2CountAccountsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, []string{"ledger"}); err != nil {
		return err
	}
	return nil
}

func (v *V2CountAccountsRequest) GetLedger() string {
	if v == nil {
		return ""
	}
	return v.Ledger
}

func (v *V2CountAccountsRequest) GetPit() *time.Time {
	if v == nil {
		return nil
	}
	return v.Pit
}

func (v *V2CountAccountsRequest) GetQuery() map[string]any {
	if v == nil {
		return nil
	}
	return v.Query
}

type V2CountAccountsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	V2ErrorResponse *shared.V2ErrorResponse
}

func (v *V2CountAccountsResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2CountAccountsResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}

func (v *V2CountAccountsResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2CountAccountsResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V2CountAccountsResponse) GetV2ErrorResponse() *shared.V2ErrorResponse {
	if v == nil {
		return nil
	}
	return v.V2ErrorResponse
}
