// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V2DeleteAccountMetadataRequest struct {
	// Use an idempotency key
	IdempotencyKey *string `header:"style=simple,explode=false,name=Idempotency-Key"`
	// Account address
	Address string `pathParam:"style=simple,explode=false,name=address"`
	// The key to remove.
	Key string `pathParam:"style=simple,explode=false,name=key"`
	// Name of the ledger.
	Ledger string `pathParam:"style=simple,explode=false,name=ledger"`
}

func (v *V2DeleteAccountMetadataRequest) GetIdempotencyKey() *string {
	if v == nil {
		return nil
	}
	return v.IdempotencyKey
}

func (v *V2DeleteAccountMetadataRequest) GetAddress() string {
	if v == nil {
		return ""
	}
	return v.Address
}

func (v *V2DeleteAccountMetadataRequest) GetKey() string {
	if v == nil {
		return ""
	}
	return v.Key
}

func (v *V2DeleteAccountMetadataRequest) GetLedger() string {
	if v == nil {
		return ""
	}
	return v.Ledger
}

type V2DeleteAccountMetadataResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	V2ErrorResponse *shared.V2ErrorResponse
}

func (v *V2DeleteAccountMetadataResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2DeleteAccountMetadataResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}

func (v *V2DeleteAccountMetadataResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2DeleteAccountMetadataResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V2DeleteAccountMetadataResponse) GetV2ErrorResponse() *shared.V2ErrorResponse {
	if v == nil {
		return nil
	}
	return v.V2ErrorResponse
}
