// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V2DeleteWorkflowRequest struct {
	// The flow id
	FlowID string `pathParam:"style=simple,explode=false,name=flowId"`
}

func (v *V2DeleteWorkflowRequest) GetFlowID() string {
	if v == nil {
		return ""
	}
	return v.FlowID
}

type V2DeleteWorkflowResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// General error
	V2Error *shared.V2Error
}

func (v *V2DeleteWorkflowResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2DeleteWorkflowResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2DeleteWorkflowResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V2DeleteWorkflowResponse) GetV2Error() *shared.V2Error {
	if v == nil {
		return nil
	}
	return v.V2Error
}
