// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V2InsertSchemaRequest struct {
	V2SchemaData shared.V2SchemaData `request:"mediaType=application/json"`
	// Name of the ledger.
	Ledger string `pathParam:"style=simple,explode=false,name=ledger"`
	// Schema version.
	Version string `pathParam:"style=simple,explode=false,name=version"`
}

func (v *V2InsertSchemaRequest) GetV2SchemaData() shared.V2SchemaData {
	if v == nil {
		return shared.V2SchemaData{}
	}
	return v.V2SchemaData
}

func (v *V2InsertSchemaRequest) GetLedger() string {
	if v == nil {
		return ""
	}
	return v.Ledger
}

func (v *V2InsertSchemaRequest) GetVersion() string {
	if v == nil {
		return ""
	}
	return v.Version
}

type V2InsertSchemaResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	V2ErrorResponse *shared.V2ErrorResponse
}

func (v *V2InsertSchemaResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2InsertSchemaResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2InsertSchemaResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V2InsertSchemaResponse) GetV2ErrorResponse() *shared.V2ErrorResponse {
	if v == nil {
		return nil
	}
	return v.V2ErrorResponse
}
