// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V2SendEventRequestBody struct {
	Name string `json:"name"`
}

func (v *V2SendEventRequestBody) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

type V2SendEventRequest struct {
	RequestBody *V2SendEventRequestBody `request:"mediaType=application/json"`
	// The instance id
	InstanceID string `pathParam:"style=simple,explode=false,name=instanceID"`
}

func (v *V2SendEventRequest) GetRequestBody() *V2SendEventRequestBody {
	if v == nil {
		return nil
	}
	return v.RequestBody
}

func (v *V2SendEventRequest) GetInstanceID() string {
	if v == nil {
		return ""
	}
	return v.InstanceID
}

type V2SendEventResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// General error
	V2Error *shared.V2Error
}

func (v *V2SendEventResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2SendEventResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2SendEventResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V2SendEventResponse) GetV2Error() *shared.V2Error {
	if v == nil {
		return nil
	}
	return v.V2Error
}
