// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V2StartPipelineRequest struct {
	// Name of the ledger.
	Ledger string `pathParam:"style=simple,explode=false,name=ledger"`
	// The pipeline id
	PipelineID string `pathParam:"style=simple,explode=false,name=pipelineID"`
}

func (v *V2StartPipelineRequest) GetLedger() string {
	if v == nil {
		return ""
	}
	return v.Ledger
}

func (v *V2StartPipelineRequest) GetPipelineID() string {
	if v == nil {
		return ""
	}
	return v.PipelineID
}

type V2StartPipelineResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	V2ErrorResponse *shared.V2ErrorResponse
}

func (v *V2StartPipelineResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V2StartPipelineResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V2StartPipelineResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V2StartPipelineResponse) GetV2ErrorResponse() *shared.V2ErrorResponse {
	if v == nil {
		return nil
	}
	return v.V2ErrorResponse
}
