// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V3DeletePoolRequest struct {
	// The pool ID
	PoolID string `pathParam:"style=simple,explode=false,name=poolID"`
}

func (v *V3DeletePoolRequest) GetPoolID() string {
	if v == nil {
		return ""
	}
	return v.PoolID
}

type V3DeletePoolResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	V3ErrorResponse *shared.V3ErrorResponse
}

func (v *V3DeletePoolResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V3DeletePoolResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V3DeletePoolResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V3DeletePoolResponse) GetV3ErrorResponse() *shared.V3ErrorResponse {
	if v == nil {
		return nil
	}
	return v.V3ErrorResponse
}
