// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V3DeletePaymentInitiationRequest struct {
	// The payment initiation ID
	PaymentInitiationID string `pathParam:"style=simple,explode=false,name=paymentInitiationID"`
}

func (v *V3DeletePaymentInitiationRequest) GetPaymentInitiationID() string {
	if v == nil {
		return ""
	}
	return v.PaymentInitiationID
}

type V3DeletePaymentInitiationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	V3ErrorResponse *shared.V3ErrorResponse
}

func (v *V3DeletePaymentInitiationResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V3DeletePaymentInitiationResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V3DeletePaymentInitiationResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V3DeletePaymentInitiationResponse) GetV3ErrorResponse() *shared.V3ErrorResponse {
	if v == nil {
		return nil
	}
	return v.V3ErrorResponse
}
