// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	"net/http"
)

type V3ForwardPaymentServiceUserToProviderRequest struct {
	// The connector ID
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorID"`
	// The payment service user ID
	PaymentServiceUserID string `pathParam:"style=simple,explode=false,name=paymentServiceUserID"`
}

func (v *V3ForwardPaymentServiceUserToProviderRequest) GetConnectorID() string {
	if v == nil {
		return ""
	}
	return v.ConnectorID
}

func (v *V3ForwardPaymentServiceUserToProviderRequest) GetPaymentServiceUserID() string {
	if v == nil {
		return ""
	}
	return v.PaymentServiceUserID
}

type V3ForwardPaymentServiceUserToProviderResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	V3ErrorResponse *shared.V3ErrorResponse
}

func (v *V3ForwardPaymentServiceUserToProviderResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *V3ForwardPaymentServiceUserToProviderResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *V3ForwardPaymentServiceUserToProviderResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}

func (v *V3ForwardPaymentServiceUserToProviderResponse) GetV3ErrorResponse() *shared.V3ErrorResponse {
	if v == nil {
		return nil
	}
	return v.V3ErrorResponse
}
