// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/formancehq/terraform-provider-stack/internal/server/sdk (interfaces: CloudSDK)
//
// Generated by this command:
//
//	mockgen -destination=cloud_generated.go -package=sdk . CloudSDK
//

// Package sdk is a generated GoMock package.
package sdk

import (
	context "context"
	http "net/http"
	reflect "reflect"

	sdk "github.com/formancehq/terraform-provider-cloud/sdk"
	gomock "go.uber.org/mock/gomock"
)

// MockCloudSDK is a mock of CloudSDK interface.
type MockCloudSDK struct {
	ctrl     *gomock.Controller
	recorder *MockCloudSDKMockRecorder
	isgomock struct{}
}

// MockCloudSDKMockRecorder is the mock recorder for MockCloudSDK.
type MockCloudSDKMockRecorder struct {
	mock *MockCloudSDK
}

// NewMockCloudSDK returns a new MockCloudSDK instance linked to the provided gomock.Controller for use in tests.
func NewMockCloudSDK(ctrl *gomock.Controller) *MockCloudSDK {
	mock := &MockCloudSDK{ctrl: ctrl}
	mock.recorder = &MockCloudSDKMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudSDK) EXPECT() *MockCloudSDKMockRecorder {
	return m.recorder
}

// GetStack mocks base method.
func (m *MockCloudSDK) GetStack(ctx context.Context, organizationID, stackID string) (*sdk.CreateStackResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStack", ctx, organizationID, stackID)
	ret0, _ := ret[0].(*sdk.CreateStackResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStack indicates an expected call of GetStack.
func (mr *MockCloudSDKMockRecorder) GetStack(ctx, organizationID, stackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStack", reflect.TypeOf((*MockCloudSDK)(nil).GetStack), ctx, organizationID, stackID)
}

// ListModules mocks base method.
func (m *MockCloudSDK) ListModules(ctx context.Context, organizationID, stackID string) (*sdk.ListModulesResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModules", ctx, organizationID, stackID)
	ret0, _ := ret[0].(*sdk.ListModulesResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListModules indicates an expected call of ListModules.
func (mr *MockCloudSDKMockRecorder) ListModules(ctx, organizationID, stackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModules", reflect.TypeOf((*MockCloudSDK)(nil).ListModules), ctx, organizationID, stackID)
}
