// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/formancehq/terraform-provider-stack/internal/server/sdk (interfaces: LedgerSdkImpl)
//
// Generated by this command:
//
//	mockgen -typed -destination=ledger_generated.go -package=sdk . LedgerSdkImpl
//

// Package sdk is a generated GoMock package.
package sdk

import (
	context "context"
	reflect "reflect"

	operations "github.com/formancehq/formance-sdk-go/v3/pkg/models/operations"
	gomock "go.uber.org/mock/gomock"
)

// MockLedgerSdkImpl is a mock of LedgerSdkImpl interface.
type MockLedgerSdkImpl struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerSdkImplMockRecorder
	isgomock struct{}
}

// MockLedgerSdkImplMockRecorder is the mock recorder for MockLedgerSdkImpl.
type MockLedgerSdkImplMockRecorder struct {
	mock *MockLedgerSdkImpl
}

// NewMockLedgerSdkImpl creates a new mock instance.
func NewMockLedgerSdkImpl(ctrl *gomock.Controller) *MockLedgerSdkImpl {
	mock := &MockLedgerSdkImpl{ctrl: ctrl}
	mock.recorder = &MockLedgerSdkImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedgerSdkImpl) EXPECT() *MockLedgerSdkImplMockRecorder {
	return m.recorder
}

// CreateLedger mocks base method.
func (m *MockLedgerSdkImpl) CreateLedger(ctx context.Context, request operations.V2CreateLedgerRequest) (*operations.V2CreateLedgerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLedger", ctx, request)
	ret0, _ := ret[0].(*operations.V2CreateLedgerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLedger indicates an expected call of CreateLedger.
func (mr *MockLedgerSdkImplMockRecorder) CreateLedger(ctx, request any) *MockLedgerSdkImplCreateLedgerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLedger", reflect.TypeOf((*MockLedgerSdkImpl)(nil).CreateLedger), ctx, request)
	return &MockLedgerSdkImplCreateLedgerCall{Call: call}
}

// MockLedgerSdkImplCreateLedgerCall wrap *gomock.Call
type MockLedgerSdkImplCreateLedgerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLedgerSdkImplCreateLedgerCall) Return(arg0 *operations.V2CreateLedgerResponse, arg1 error) *MockLedgerSdkImplCreateLedgerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLedgerSdkImplCreateLedgerCall) Do(f func(context.Context, operations.V2CreateLedgerRequest) (*operations.V2CreateLedgerResponse, error)) *MockLedgerSdkImplCreateLedgerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLedgerSdkImplCreateLedgerCall) DoAndReturn(f func(context.Context, operations.V2CreateLedgerRequest) (*operations.V2CreateLedgerResponse, error)) *MockLedgerSdkImplCreateLedgerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteLedger mocks base method.
func (m *MockLedgerSdkImpl) DeleteLedger(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLedger", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLedger indicates an expected call of DeleteLedger.
func (mr *MockLedgerSdkImplMockRecorder) DeleteLedger(ctx, name any) *MockLedgerSdkImplDeleteLedgerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLedger", reflect.TypeOf((*MockLedgerSdkImpl)(nil).DeleteLedger), ctx, name)
	return &MockLedgerSdkImplDeleteLedgerCall{Call: call}
}

// MockLedgerSdkImplDeleteLedgerCall wrap *gomock.Call
type MockLedgerSdkImplDeleteLedgerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLedgerSdkImplDeleteLedgerCall) Return(arg0 error) *MockLedgerSdkImplDeleteLedgerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLedgerSdkImplDeleteLedgerCall) Do(f func(context.Context, string) error) *MockLedgerSdkImplDeleteLedgerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLedgerSdkImplDeleteLedgerCall) DoAndReturn(f func(context.Context, string) error) *MockLedgerSdkImplDeleteLedgerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetLedger mocks base method.
func (m *MockLedgerSdkImpl) GetLedger(ctx context.Context, request operations.V2GetLedgerRequest) (*operations.V2GetLedgerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedger", ctx, request)
	ret0, _ := ret[0].(*operations.V2GetLedgerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedger indicates an expected call of GetLedger.
func (mr *MockLedgerSdkImplMockRecorder) GetLedger(ctx, request any) *MockLedgerSdkImplGetLedgerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedger", reflect.TypeOf((*MockLedgerSdkImpl)(nil).GetLedger), ctx, request)
	return &MockLedgerSdkImplGetLedgerCall{Call: call}
}

// MockLedgerSdkImplGetLedgerCall wrap *gomock.Call
type MockLedgerSdkImplGetLedgerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLedgerSdkImplGetLedgerCall) Return(arg0 *operations.V2GetLedgerResponse, arg1 error) *MockLedgerSdkImplGetLedgerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLedgerSdkImplGetLedgerCall) Do(f func(context.Context, operations.V2GetLedgerRequest) (*operations.V2GetLedgerResponse, error)) *MockLedgerSdkImplGetLedgerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLedgerSdkImplGetLedgerCall) DoAndReturn(f func(context.Context, operations.V2GetLedgerRequest) (*operations.V2GetLedgerResponse, error)) *MockLedgerSdkImplGetLedgerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSchema mocks base method.
func (m *MockLedgerSdkImpl) GetSchema(ctx context.Context, request operations.V2GetSchemaRequest) (*operations.V2GetSchemaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchema", ctx, request)
	ret0, _ := ret[0].(*operations.V2GetSchemaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchema indicates an expected call of GetSchema.
func (mr *MockLedgerSdkImplMockRecorder) GetSchema(ctx, request any) *MockLedgerSdkImplGetSchemaCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchema", reflect.TypeOf((*MockLedgerSdkImpl)(nil).GetSchema), ctx, request)
	return &MockLedgerSdkImplGetSchemaCall{Call: call}
}

// MockLedgerSdkImplGetSchemaCall wrap *gomock.Call
type MockLedgerSdkImplGetSchemaCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLedgerSdkImplGetSchemaCall) Return(arg0 *operations.V2GetSchemaResponse, arg1 error) *MockLedgerSdkImplGetSchemaCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLedgerSdkImplGetSchemaCall) Do(f func(context.Context, operations.V2GetSchemaRequest) (*operations.V2GetSchemaResponse, error)) *MockLedgerSdkImplGetSchemaCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLedgerSdkImplGetSchemaCall) DoAndReturn(f func(context.Context, operations.V2GetSchemaRequest) (*operations.V2GetSchemaResponse, error)) *MockLedgerSdkImplGetSchemaCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InsertSchema mocks base method.
func (m *MockLedgerSdkImpl) InsertSchema(ctx context.Context, request operations.V2InsertSchemaRequest) (*operations.V2InsertSchemaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSchema", ctx, request)
	ret0, _ := ret[0].(*operations.V2InsertSchemaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertSchema indicates an expected call of InsertSchema.
func (mr *MockLedgerSdkImplMockRecorder) InsertSchema(ctx, request any) *MockLedgerSdkImplInsertSchemaCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSchema", reflect.TypeOf((*MockLedgerSdkImpl)(nil).InsertSchema), ctx, request)
	return &MockLedgerSdkImplInsertSchemaCall{Call: call}
}

// MockLedgerSdkImplInsertSchemaCall wrap *gomock.Call
type MockLedgerSdkImplInsertSchemaCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLedgerSdkImplInsertSchemaCall) Return(arg0 *operations.V2InsertSchemaResponse, arg1 error) *MockLedgerSdkImplInsertSchemaCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLedgerSdkImplInsertSchemaCall) Do(f func(context.Context, operations.V2InsertSchemaRequest) (*operations.V2InsertSchemaResponse, error)) *MockLedgerSdkImplInsertSchemaCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLedgerSdkImplInsertSchemaCall) DoAndReturn(f func(context.Context, operations.V2InsertSchemaRequest) (*operations.V2InsertSchemaResponse, error)) *MockLedgerSdkImplInsertSchemaCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateLedgerMetadata mocks base method.
func (m *MockLedgerSdkImpl) UpdateLedgerMetadata(ctx context.Context, request operations.V2UpdateLedgerMetadataRequest) (*operations.V2UpdateLedgerMetadataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLedgerMetadata", ctx, request)
	ret0, _ := ret[0].(*operations.V2UpdateLedgerMetadataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLedgerMetadata indicates an expected call of UpdateLedgerMetadata.
func (mr *MockLedgerSdkImplMockRecorder) UpdateLedgerMetadata(ctx, request any) *MockLedgerSdkImplUpdateLedgerMetadataCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLedgerMetadata", reflect.TypeOf((*MockLedgerSdkImpl)(nil).UpdateLedgerMetadata), ctx, request)
	return &MockLedgerSdkImplUpdateLedgerMetadataCall{Call: call}
}

// MockLedgerSdkImplUpdateLedgerMetadataCall wrap *gomock.Call
type MockLedgerSdkImplUpdateLedgerMetadataCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLedgerSdkImplUpdateLedgerMetadataCall) Return(arg0 *operations.V2UpdateLedgerMetadataResponse, arg1 error) *MockLedgerSdkImplUpdateLedgerMetadataCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLedgerSdkImplUpdateLedgerMetadataCall) Do(f func(context.Context, operations.V2UpdateLedgerMetadataRequest) (*operations.V2UpdateLedgerMetadataResponse, error)) *MockLedgerSdkImplUpdateLedgerMetadataCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLedgerSdkImplUpdateLedgerMetadataCall) DoAndReturn(f func(context.Context, operations.V2UpdateLedgerMetadataRequest) (*operations.V2UpdateLedgerMetadataResponse, error)) *MockLedgerSdkImplUpdateLedgerMetadataCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
