// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/formancehq/terraform-provider-stack/internal/server/sdk (interfaces: PaymentsSdkImpl)
//
// Generated by this command:
//
//	mockgen -typed -destination=payments_generated.go -package=sdk . PaymentsSdkImpl
//

// Package sdk is a generated GoMock package.
package sdk

import (
	context "context"
	reflect "reflect"

	operations "github.com/formancehq/formance-sdk-go/v3/pkg/models/operations"
	shared "github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentsSdkImpl is a mock of PaymentsSdkImpl interface.
type MockPaymentsSdkImpl struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentsSdkImplMockRecorder
	isgomock struct{}
}

// MockPaymentsSdkImplMockRecorder is the mock recorder for MockPaymentsSdkImpl.
type MockPaymentsSdkImplMockRecorder struct {
	mock *MockPaymentsSdkImpl
}

// NewMockPaymentsSdkImpl creates a new mock instance.
func NewMockPaymentsSdkImpl(ctrl *gomock.Controller) *MockPaymentsSdkImpl {
	mock := &MockPaymentsSdkImpl{ctrl: ctrl}
	mock.recorder = &MockPaymentsSdkImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentsSdkImpl) EXPECT() *MockPaymentsSdkImplMockRecorder {
	return m.recorder
}

// AddAccountToPool mocks base method.
func (m *MockPaymentsSdkImpl) AddAccountToPool(ctx context.Context, request operations.V3AddAccountToPoolRequest) (*operations.V3AddAccountToPoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAccountToPool", ctx, request)
	ret0, _ := ret[0].(*operations.V3AddAccountToPoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAccountToPool indicates an expected call of AddAccountToPool.
func (mr *MockPaymentsSdkImplMockRecorder) AddAccountToPool(ctx, request any) *MockPaymentsSdkImplAddAccountToPoolCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAccountToPool", reflect.TypeOf((*MockPaymentsSdkImpl)(nil).AddAccountToPool), ctx, request)
	return &MockPaymentsSdkImplAddAccountToPoolCall{Call: call}
}

// MockPaymentsSdkImplAddAccountToPoolCall wrap *gomock.Call
type MockPaymentsSdkImplAddAccountToPoolCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPaymentsSdkImplAddAccountToPoolCall) Return(arg0 *operations.V3AddAccountToPoolResponse, arg1 error) *MockPaymentsSdkImplAddAccountToPoolCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPaymentsSdkImplAddAccountToPoolCall) Do(f func(context.Context, operations.V3AddAccountToPoolRequest) (*operations.V3AddAccountToPoolResponse, error)) *MockPaymentsSdkImplAddAccountToPoolCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPaymentsSdkImplAddAccountToPoolCall) DoAndReturn(f func(context.Context, operations.V3AddAccountToPoolRequest) (*operations.V3AddAccountToPoolResponse, error)) *MockPaymentsSdkImplAddAccountToPoolCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateConnector mocks base method.
func (m *MockPaymentsSdkImpl) CreateConnector(ctx context.Context, request operations.V3InstallConnectorRequest) (*operations.V3InstallConnectorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConnector", ctx, request)
	ret0, _ := ret[0].(*operations.V3InstallConnectorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConnector indicates an expected call of CreateConnector.
func (mr *MockPaymentsSdkImplMockRecorder) CreateConnector(ctx, request any) *MockPaymentsSdkImplCreateConnectorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConnector", reflect.TypeOf((*MockPaymentsSdkImpl)(nil).CreateConnector), ctx, request)
	return &MockPaymentsSdkImplCreateConnectorCall{Call: call}
}

// MockPaymentsSdkImplCreateConnectorCall wrap *gomock.Call
type MockPaymentsSdkImplCreateConnectorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPaymentsSdkImplCreateConnectorCall) Return(arg0 *operations.V3InstallConnectorResponse, arg1 error) *MockPaymentsSdkImplCreateConnectorCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPaymentsSdkImplCreateConnectorCall) Do(f func(context.Context, operations.V3InstallConnectorRequest) (*operations.V3InstallConnectorResponse, error)) *MockPaymentsSdkImplCreateConnectorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPaymentsSdkImplCreateConnectorCall) DoAndReturn(f func(context.Context, operations.V3InstallConnectorRequest) (*operations.V3InstallConnectorResponse, error)) *MockPaymentsSdkImplCreateConnectorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreatePool mocks base method.
func (m *MockPaymentsSdkImpl) CreatePool(ctx context.Context, request *shared.V3CreatePoolRequest) (*operations.V3CreatePoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePool", ctx, request)
	ret0, _ := ret[0].(*operations.V3CreatePoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePool indicates an expected call of CreatePool.
func (mr *MockPaymentsSdkImplMockRecorder) CreatePool(ctx, request any) *MockPaymentsSdkImplCreatePoolCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePool", reflect.TypeOf((*MockPaymentsSdkImpl)(nil).CreatePool), ctx, request)
	return &MockPaymentsSdkImplCreatePoolCall{Call: call}
}

// MockPaymentsSdkImplCreatePoolCall wrap *gomock.Call
type MockPaymentsSdkImplCreatePoolCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPaymentsSdkImplCreatePoolCall) Return(arg0 *operations.V3CreatePoolResponse, arg1 error) *MockPaymentsSdkImplCreatePoolCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPaymentsSdkImplCreatePoolCall) Do(f func(context.Context, *shared.V3CreatePoolRequest) (*operations.V3CreatePoolResponse, error)) *MockPaymentsSdkImplCreatePoolCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPaymentsSdkImplCreatePoolCall) DoAndReturn(f func(context.Context, *shared.V3CreatePoolRequest) (*operations.V3CreatePoolResponse, error)) *MockPaymentsSdkImplCreatePoolCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteConnector mocks base method.
func (m *MockPaymentsSdkImpl) DeleteConnector(ctx context.Context, request operations.V3UninstallConnectorRequest) (*operations.V3UninstallConnectorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConnector", ctx, request)
	ret0, _ := ret[0].(*operations.V3UninstallConnectorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteConnector indicates an expected call of DeleteConnector.
func (mr *MockPaymentsSdkImplMockRecorder) DeleteConnector(ctx, request any) *MockPaymentsSdkImplDeleteConnectorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConnector", reflect.TypeOf((*MockPaymentsSdkImpl)(nil).DeleteConnector), ctx, request)
	return &MockPaymentsSdkImplDeleteConnectorCall{Call: call}
}

// MockPaymentsSdkImplDeleteConnectorCall wrap *gomock.Call
type MockPaymentsSdkImplDeleteConnectorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPaymentsSdkImplDeleteConnectorCall) Return(arg0 *operations.V3UninstallConnectorResponse, arg1 error) *MockPaymentsSdkImplDeleteConnectorCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPaymentsSdkImplDeleteConnectorCall) Do(f func(context.Context, operations.V3UninstallConnectorRequest) (*operations.V3UninstallConnectorResponse, error)) *MockPaymentsSdkImplDeleteConnectorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPaymentsSdkImplDeleteConnectorCall) DoAndReturn(f func(context.Context, operations.V3UninstallConnectorRequest) (*operations.V3UninstallConnectorResponse, error)) *MockPaymentsSdkImplDeleteConnectorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeletePool mocks base method.
func (m *MockPaymentsSdkImpl) DeletePool(ctx context.Context, request operations.V3DeletePoolRequest) (*operations.V3DeletePoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePool", ctx, request)
	ret0, _ := ret[0].(*operations.V3DeletePoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePool indicates an expected call of DeletePool.
func (mr *MockPaymentsSdkImplMockRecorder) DeletePool(ctx, request any) *MockPaymentsSdkImplDeletePoolCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePool", reflect.TypeOf((*MockPaymentsSdkImpl)(nil).DeletePool), ctx, request)
	return &MockPaymentsSdkImplDeletePoolCall{Call: call}
}

// MockPaymentsSdkImplDeletePoolCall wrap *gomock.Call
type MockPaymentsSdkImplDeletePoolCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPaymentsSdkImplDeletePoolCall) Return(arg0 *operations.V3DeletePoolResponse, arg1 error) *MockPaymentsSdkImplDeletePoolCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPaymentsSdkImplDeletePoolCall) Do(f func(context.Context, operations.V3DeletePoolRequest) (*operations.V3DeletePoolResponse, error)) *MockPaymentsSdkImplDeletePoolCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPaymentsSdkImplDeletePoolCall) DoAndReturn(f func(context.Context, operations.V3DeletePoolRequest) (*operations.V3DeletePoolResponse, error)) *MockPaymentsSdkImplDeletePoolCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetConnector mocks base method.
func (m *MockPaymentsSdkImpl) GetConnector(ctx context.Context, request operations.V3GetConnectorConfigRequest) (*operations.V3GetConnectorConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnector", ctx, request)
	ret0, _ := ret[0].(*operations.V3GetConnectorConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnector indicates an expected call of GetConnector.
func (mr *MockPaymentsSdkImplMockRecorder) GetConnector(ctx, request any) *MockPaymentsSdkImplGetConnectorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnector", reflect.TypeOf((*MockPaymentsSdkImpl)(nil).GetConnector), ctx, request)
	return &MockPaymentsSdkImplGetConnectorCall{Call: call}
}

// MockPaymentsSdkImplGetConnectorCall wrap *gomock.Call
type MockPaymentsSdkImplGetConnectorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPaymentsSdkImplGetConnectorCall) Return(arg0 *operations.V3GetConnectorConfigResponse, arg1 error) *MockPaymentsSdkImplGetConnectorCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPaymentsSdkImplGetConnectorCall) Do(f func(context.Context, operations.V3GetConnectorConfigRequest) (*operations.V3GetConnectorConfigResponse, error)) *MockPaymentsSdkImplGetConnectorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPaymentsSdkImplGetConnectorCall) DoAndReturn(f func(context.Context, operations.V3GetConnectorConfigRequest) (*operations.V3GetConnectorConfigResponse, error)) *MockPaymentsSdkImplGetConnectorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPool mocks base method.
func (m *MockPaymentsSdkImpl) GetPool(ctx context.Context, request operations.V3GetPoolRequest) (*operations.V3GetPoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPool", ctx, request)
	ret0, _ := ret[0].(*operations.V3GetPoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPool indicates an expected call of GetPool.
func (mr *MockPaymentsSdkImplMockRecorder) GetPool(ctx, request any) *MockPaymentsSdkImplGetPoolCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPool", reflect.TypeOf((*MockPaymentsSdkImpl)(nil).GetPool), ctx, request)
	return &MockPaymentsSdkImplGetPoolCall{Call: call}
}

// MockPaymentsSdkImplGetPoolCall wrap *gomock.Call
type MockPaymentsSdkImplGetPoolCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPaymentsSdkImplGetPoolCall) Return(arg0 *operations.V3GetPoolResponse, arg1 error) *MockPaymentsSdkImplGetPoolCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPaymentsSdkImplGetPoolCall) Do(f func(context.Context, operations.V3GetPoolRequest) (*operations.V3GetPoolResponse, error)) *MockPaymentsSdkImplGetPoolCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPaymentsSdkImplGetPoolCall) DoAndReturn(f func(context.Context, operations.V3GetPoolRequest) (*operations.V3GetPoolResponse, error)) *MockPaymentsSdkImplGetPoolCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveAccountFromPool mocks base method.
func (m *MockPaymentsSdkImpl) RemoveAccountFromPool(ctx context.Context, request operations.V3RemoveAccountFromPoolRequest) (*operations.V3RemoveAccountFromPoolResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAccountFromPool", ctx, request)
	ret0, _ := ret[0].(*operations.V3RemoveAccountFromPoolResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveAccountFromPool indicates an expected call of RemoveAccountFromPool.
func (mr *MockPaymentsSdkImplMockRecorder) RemoveAccountFromPool(ctx, request any) *MockPaymentsSdkImplRemoveAccountFromPoolCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAccountFromPool", reflect.TypeOf((*MockPaymentsSdkImpl)(nil).RemoveAccountFromPool), ctx, request)
	return &MockPaymentsSdkImplRemoveAccountFromPoolCall{Call: call}
}

// MockPaymentsSdkImplRemoveAccountFromPoolCall wrap *gomock.Call
type MockPaymentsSdkImplRemoveAccountFromPoolCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPaymentsSdkImplRemoveAccountFromPoolCall) Return(arg0 *operations.V3RemoveAccountFromPoolResponse, arg1 error) *MockPaymentsSdkImplRemoveAccountFromPoolCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPaymentsSdkImplRemoveAccountFromPoolCall) Do(f func(context.Context, operations.V3RemoveAccountFromPoolRequest) (*operations.V3RemoveAccountFromPoolResponse, error)) *MockPaymentsSdkImplRemoveAccountFromPoolCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPaymentsSdkImplRemoveAccountFromPoolCall) DoAndReturn(f func(context.Context, operations.V3RemoveAccountFromPoolRequest) (*operations.V3RemoveAccountFromPoolResponse, error)) *MockPaymentsSdkImplRemoveAccountFromPoolCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateConnector mocks base method.
func (m *MockPaymentsSdkImpl) UpdateConnector(ctx context.Context, request operations.V3UpdateConnectorConfigRequest) (*operations.V3UpdateConnectorConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConnector", ctx, request)
	ret0, _ := ret[0].(*operations.V3UpdateConnectorConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConnector indicates an expected call of UpdateConnector.
func (mr *MockPaymentsSdkImplMockRecorder) UpdateConnector(ctx, request any) *MockPaymentsSdkImplUpdateConnectorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConnector", reflect.TypeOf((*MockPaymentsSdkImpl)(nil).UpdateConnector), ctx, request)
	return &MockPaymentsSdkImplUpdateConnectorCall{Call: call}
}

// MockPaymentsSdkImplUpdateConnectorCall wrap *gomock.Call
type MockPaymentsSdkImplUpdateConnectorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPaymentsSdkImplUpdateConnectorCall) Return(arg0 *operations.V3UpdateConnectorConfigResponse, arg1 error) *MockPaymentsSdkImplUpdateConnectorCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPaymentsSdkImplUpdateConnectorCall) Do(f func(context.Context, operations.V3UpdateConnectorConfigRequest) (*operations.V3UpdateConnectorConfigResponse, error)) *MockPaymentsSdkImplUpdateConnectorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPaymentsSdkImplUpdateConnectorCall) DoAndReturn(f func(context.Context, operations.V3UpdateConnectorConfigRequest) (*operations.V3UpdateConnectorConfigResponse, error)) *MockPaymentsSdkImplUpdateConnectorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
