// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/formancehq/terraform-provider-stack/internal/server/sdk (interfaces: ReconciliationSdkImpl)
//
// Generated by this command:
//
//	mockgen -typed -destination=reconciliation_generated.go -package=sdk . ReconciliationSdkImpl
//

// Package sdk is a generated GoMock package.
package sdk

import (
	context "context"
	reflect "reflect"

	operations "github.com/formancehq/formance-sdk-go/v3/pkg/models/operations"
	shared "github.com/formancehq/formance-sdk-go/v3/pkg/models/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockReconciliationSdkImpl is a mock of ReconciliationSdkImpl interface.
type MockReconciliationSdkImpl struct {
	ctrl     *gomock.Controller
	recorder *MockReconciliationSdkImplMockRecorder
	isgomock struct{}
}

// MockReconciliationSdkImplMockRecorder is the mock recorder for MockReconciliationSdkImpl.
type MockReconciliationSdkImplMockRecorder struct {
	mock *MockReconciliationSdkImpl
}

// NewMockReconciliationSdkImpl creates a new mock instance.
func NewMockReconciliationSdkImpl(ctrl *gomock.Controller) *MockReconciliationSdkImpl {
	mock := &MockReconciliationSdkImpl{ctrl: ctrl}
	mock.recorder = &MockReconciliationSdkImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReconciliationSdkImpl) EXPECT() *MockReconciliationSdkImplMockRecorder {
	return m.recorder
}

// CreatePolicy mocks base method.
func (m *MockReconciliationSdkImpl) CreatePolicy(ctx context.Context, request shared.PolicyRequest, opts ...operations.Option) (*operations.CreatePolicyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreatePolicy", varargs...)
	ret0, _ := ret[0].(*operations.CreatePolicyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePolicy indicates an expected call of CreatePolicy.
func (mr *MockReconciliationSdkImplMockRecorder) CreatePolicy(ctx, request any, opts ...any) *MockReconciliationSdkImplCreatePolicyCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, request}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePolicy", reflect.TypeOf((*MockReconciliationSdkImpl)(nil).CreatePolicy), varargs...)
	return &MockReconciliationSdkImplCreatePolicyCall{Call: call}
}

// MockReconciliationSdkImplCreatePolicyCall wrap *gomock.Call
type MockReconciliationSdkImplCreatePolicyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReconciliationSdkImplCreatePolicyCall) Return(arg0 *operations.CreatePolicyResponse, arg1 error) *MockReconciliationSdkImplCreatePolicyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReconciliationSdkImplCreatePolicyCall) Do(f func(context.Context, shared.PolicyRequest, ...operations.Option) (*operations.CreatePolicyResponse, error)) *MockReconciliationSdkImplCreatePolicyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReconciliationSdkImplCreatePolicyCall) DoAndReturn(f func(context.Context, shared.PolicyRequest, ...operations.Option) (*operations.CreatePolicyResponse, error)) *MockReconciliationSdkImplCreatePolicyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeletePolicy mocks base method.
func (m *MockReconciliationSdkImpl) DeletePolicy(ctx context.Context, request operations.DeletePolicyRequest, opts ...operations.Option) (*operations.DeletePolicyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeletePolicy", varargs...)
	ret0, _ := ret[0].(*operations.DeletePolicyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePolicy indicates an expected call of DeletePolicy.
func (mr *MockReconciliationSdkImplMockRecorder) DeletePolicy(ctx, request any, opts ...any) *MockReconciliationSdkImplDeletePolicyCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, request}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePolicy", reflect.TypeOf((*MockReconciliationSdkImpl)(nil).DeletePolicy), varargs...)
	return &MockReconciliationSdkImplDeletePolicyCall{Call: call}
}

// MockReconciliationSdkImplDeletePolicyCall wrap *gomock.Call
type MockReconciliationSdkImplDeletePolicyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReconciliationSdkImplDeletePolicyCall) Return(arg0 *operations.DeletePolicyResponse, arg1 error) *MockReconciliationSdkImplDeletePolicyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReconciliationSdkImplDeletePolicyCall) Do(f func(context.Context, operations.DeletePolicyRequest, ...operations.Option) (*operations.DeletePolicyResponse, error)) *MockReconciliationSdkImplDeletePolicyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReconciliationSdkImplDeletePolicyCall) DoAndReturn(f func(context.Context, operations.DeletePolicyRequest, ...operations.Option) (*operations.DeletePolicyResponse, error)) *MockReconciliationSdkImplDeletePolicyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPolicy mocks base method.
func (m *MockReconciliationSdkImpl) GetPolicy(ctx context.Context, request operations.GetPolicyRequest, opts ...operations.Option) (*operations.GetPolicyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, request}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPolicy", varargs...)
	ret0, _ := ret[0].(*operations.GetPolicyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicy indicates an expected call of GetPolicy.
func (mr *MockReconciliationSdkImplMockRecorder) GetPolicy(ctx, request any, opts ...any) *MockReconciliationSdkImplGetPolicyCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, request}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicy", reflect.TypeOf((*MockReconciliationSdkImpl)(nil).GetPolicy), varargs...)
	return &MockReconciliationSdkImplGetPolicyCall{Call: call}
}

// MockReconciliationSdkImplGetPolicyCall wrap *gomock.Call
type MockReconciliationSdkImplGetPolicyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReconciliationSdkImplGetPolicyCall) Return(arg0 *operations.GetPolicyResponse, arg1 error) *MockReconciliationSdkImplGetPolicyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReconciliationSdkImplGetPolicyCall) Do(f func(context.Context, operations.GetPolicyRequest, ...operations.Option) (*operations.GetPolicyResponse, error)) *MockReconciliationSdkImplGetPolicyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReconciliationSdkImplGetPolicyCall) DoAndReturn(f func(context.Context, operations.GetPolicyRequest, ...operations.Option) (*operations.GetPolicyResponse, error)) *MockReconciliationSdkImplGetPolicyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
