// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/formancehq/terraform-provider-stack/internal/server/sdk (interfaces: StackSdkImpl)
//
// Generated by this command:
//
//	mockgen -destination=stack_generated.go -package=sdk . StackSdkImpl
//

// Package sdk is a generated GoMock package.
package sdk

import (
	gomock "go.uber.org/mock/gomock"
)

// MockStackSdkImpl is a mock of StackSdkImpl interface.
type MockStackSdkImpl struct {
	ctrl     *gomock.Controller
	recorder *MockStackSdkImplMockRecorder
	isgomock struct{}
}

// MockStackSdkImplMockRecorder is the mock recorder for MockStackSdkImpl.
type MockStackSdkImplMockRecorder struct {
	mock *MockStackSdkImpl
}

// NewMockStackSdkImpl creates a new mock instance.
func NewMockStackSdkImpl(ctrl *gomock.Controller) *MockStackSdkImpl {
	mock := &MockStackSdkImpl{ctrl: ctrl}
	mock.recorder = &MockStackSdkImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStackSdkImpl) EXPECT() *MockStackSdkImplMockRecorder {
	return m.recorder
}
