// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/formancehq/terraform-provider-stack/pkg (interfaces: TokenProviderImpl)
//
// Generated by this command:
//
//	mockgen -destination=tokenprovider_generated.go -package=pkg . TokenProviderImpl
//

// Package pkg is a generated GoMock package.
package pkg

import (
	context "context"
	reflect "reflect"

	pkg "github.com/formancehq/terraform-provider-cloud/pkg"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenProviderImpl is a mock of TokenProviderImpl interface.
type MockTokenProviderImpl struct {
	ctrl     *gomock.Controller
	recorder *MockTokenProviderImplMockRecorder
	isgomock struct{}
}

// MockTokenProviderImplMockRecorder is the mock recorder for MockTokenProviderImpl.
type MockTokenProviderImplMockRecorder struct {
	mock *MockTokenProviderImpl
}

// NewMockTokenProviderImpl returns a new MockTokenProviderImpl initialized with the provided gomock.Controller.
func NewMockTokenProviderImpl(ctrl *gomock.Controller) *MockTokenProviderImpl {
	mock := &MockTokenProviderImpl{ctrl: ctrl}
	mock.recorder = &MockTokenProviderImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenProviderImpl) EXPECT() *MockTokenProviderImplMockRecorder {
	return m.recorder
}

// StackSecurityToken mocks base method.
func (m *MockTokenProviderImpl) StackSecurityToken(ctx context.Context) (*pkg.TokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StackSecurityToken", ctx)
	ret0, _ := ret[0].(*pkg.TokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StackSecurityToken indicates an expected call of StackSecurityToken.
func (mr *MockTokenProviderImplMockRecorder) StackSecurityToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StackSecurityToken", reflect.TypeOf((*MockTokenProviderImpl)(nil).StackSecurityToken), ctx)
}
