name: Release
on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  contents: write
jobs:
  Release:
    runs-on: "shipfox-4vcpu-ubuntu-2404"
    steps:
      - uses: 'actions/checkout@v4'
      - name: Setup Env
        uses: ./.github/actions/default
        with:
          token: ${{ secrets.NUMARY_GITHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "NumaryBot"
          password: ${{ secrets.NUMARY_GITHUB_TOKEN }}
      - run: >
          nix develop --impure --command just release

        env:
          GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      - name: Add the OpenAPI file to the release assets
        run: >
          gh release upload ${{github.ref_name}} ./openapi.yaml#openapi.yaml

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
